#!/bin/bash
#cc -Wall -Werror -Wextra -D BUFFER_SIZE=10 -g get_main.c get_next_line.c get_next_line_utils.c && ./a.out
cc -Wall -Werror -Wextra -g get_main.c get_next_line.c get_next_line_utils.c && ./a.out
#cc -Wall -Werror -Wextra -g get_main.c get_next_line.c get_next_line_utils.c && valgrind --tool=memcheck --track-origins=yes --leak-check=full -s ./a.out
#cc -Wall -Werror -Wextra -D BUFFER_SIZE=10 -g get_main.c get_next_line.c get_next_line_utils.c && valgrind --tool=memcheck --track-origins=yes --leak-check=full --show-leak-kinds=all -s ./a.out
