#!/bin/bash
cc -Wall -Werror -Wextra -D BUFFER_SIZE=4 get_main.c ../../get_next_line_no42git/get_next_line.c ../../get_next_line_no42git/get_next_line_utils.c && ./a.out
#cc -Wall -Werror -Wextra -D get_main.c get_next_line.c get_next_line_utils.c && ./a.out
